context:
  version: "0.1.0"

package:
  name: myutils

  version: ${{ version }}

source:
  url: https://github.com/mikecuoco/myutils/releases/download/57/myutils-0.1.0.tar.gz
  sha256: c96d80f485f9a3d546f587adf0a041fc8204cb4e3c09576392982d29acd7abc1

build:
  noarch: python
  script: poetry install --no-dev

requirements:
  # note that there is no build section

  host:
    - pip
    - poetry
    - python =3.10
    - setuptools
    - wheel
  run:
    - pandas>=2
    - numpy>=2
    - pyranges==0.0.124
    - anndata>=0.9.2

about:
  homepage: https://github.com/mikecuoco/myutils
