context:
  version: "0.1.0"
package:
  name: myutils
  version: ${{ version }}
source:
  url: https://github.com/mikecuoco/myutils/releases/download/86/myutils-0.1.0.tar.gz
  sha256: "e1a31c5684ce11dbef9c333c54ed7252dba764ba1a1051e7954e6a3188cce505"
build:
  noarch: python
  script: poetry install --no-dev
requirements:
  # note that there is no build section
  host:
    - pip
    - poetry
    - python =3.10
    - setuptools
    - wheel
  run:
    - pandas>=2
    - numpy>=2
    - pyranges==0.0.124
    - anndata>=0.9.2
about:
  homepage: https://github.com/mikecuoco/myutils
