context:
  version: "0.1.1"
package:
  name: myutils
  version: ${{ version }}
source:
  url: https://github.com/mikecuoco/myutils/releases/download/106/myutils-0.1.1.tar.gz
  sha256: "bc2ff79cdc9e6839febe8cb3783167609c7161d664cb3b3a478d815952204067"
build:
  noarch: python
  script: |
    poetry build
    pip install dist/*.tar.gz
requirements:
  host:
    - poetry
    - pip
    - python>=3.10,<3.12
  run:
    - python>=3.10,<3.12
    - pandas>=2
    - numpy>=2
    - pyranges>=0.1.2
    - anndata>=0.9.2,<0.10
tests:
  - python:
      imports:
        - myutils
about:
  homepage: https://github.com/mikecuoco/myutils
