context:
  version: "0.1.2"
package:
  name: myutils
  version: ${{ version }}
source:
  url: https://github.com/mikecuoco/myutils/releases/download/107/myutils-0.1.2.tar.gz
  sha256: "8127eb4e7d62f537e32b93c1c7656c6722d1f63d11640c78f3334503445ad106"
build:
  noarch: python
  script: |
    poetry install --no-dev
    poetry build
    pip install dist/*.tar.gz
requirements:
  host:
    - poetry-core >= 1.0.0
    - pip
    - python>=3.10,<3.12
  run:
    - python>=3.10,<3.12
    - pandas>=2
    - numpy>=2
    - pyranges>=0.1.2
    - anndata>=0.9.2,<0.10
tests:
  - python:
      imports:
        - myutils
      pip_check: true
about:
  homepage: https://github.com/mikecuoco/myutils
