context:
  version: "0.1.0"
package:
  name: myutils
  version: ${{ version }}
source:
  url: https://github.com/mikecuoco/myutils/releases/download/98/myutils-0.1.0.tar.gz
  sha256: "ea8ccfac2262023cb16d451273b0d578655cc358f338bec7e8064e8493a28ff8"
build:
  noarch: python
  script: poetry install --no-dev
requirements:
  # note that there is no build section
  host:
    - pip
    - poetry
    - python =3.10
    - setuptools
    - wheel
  run:
    - pandas>=2
    - numpy>=2
    - pyranges==0.0.124
    - anndata>=0.9.2
about:
  homepage: https://github.com/mikecuoco/myutils
